name: Build Atlantis Image

on:
  push:
    branches: [main]
    paths:
      - "images/atlantis/**"
      - ".github/workflows/build-atlantis-image.yml"

permissions:
  id-token: write
  contents: read
  packages: write

env:
  PROJECT_ID: f4e-infra-prd
  REGION: europe-west1
  GAR_REPOSITORY: containers
  IMAGE: atlantis
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Google Auth
      #   id: auth
      #   uses: google-github-actions/auth@v2
      #   with:
      #     workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
      #     service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      #     token_format: 'access_token'

      # - name: Login to Artifact Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGION }}-docker.pkg.dev
      #     username: oauth2accesstoken
      #     password: ${{ steps.auth.outputs.access_token }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: images/atlantis
          platforms: linux/amd64 ,linux/arm64
          push: true
          # tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE }}:${{ github.sha }}
